# Generated by Django 3.1.2 on 2022-03-30 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngoname', models.TextField(max_length=191)),
                ('foodName', models.TextField(max_length=191)),
                ('mobile', models.CharField(max_length=40)),
                ('address', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=191)),
                ('companyName', models.TextField(max_length=191)),
                ('number', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('foodName', models.TextField(max_length=191)),
                ('foodImage', models.ImageField(blank=True, null=True, upload_to='static/pics')),
                ('inputState', models.TextField(max_length=50)),
                ('quantity', models.TextField(max_length=50)),
                ('hours', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=500, null=True)),
                ('status', models.BooleanField(default=False)),
                ('donationdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('by', models.CharField(default='food', max_length=20, null=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NGOExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('joindate', models.DateField(auto_now_add=True)),
                ('mobile', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonarExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
