# Generated by Django 3.1.2 on 2022-03-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
