# Generated by Django 3.1.2 on 2022-03-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20220330_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donarextra',
            name='company_name',
            field=models.CharField(max_length=191),
        ),
    ]
