# Generated by Django 3.1.2 on 2022-03-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20220330_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='foodName',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='claim',
            name='ngoname',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='donation',
            name='companyName',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='donation',
            name='foodName',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='donation',
            name='hours',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='inputState',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='username',
            field=models.CharField(max_length=191),
        ),
    ]
